# Generated by Django 4.1.1 on 2022-09-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0008_choice_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="votes",
            field=models.IntegerField(default=0, verbose_name="투표"),
        ),
        migrations.AlterField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(verbose_name="작성날짜"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(max_length=200, verbose_name="질문"),
        ),
    ]
